events {}

http {
    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Station Service
        location /station/ {
            proxy_pass http://station-app:8082/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User Service
        #location /user/ {
        #    proxy_pass http://user-app:8081/;
        #    proxy_set_header Host $host;
        #    proxy_set_header X-Real-IP $remote_addr;
        #}
    }
}

